export const APP_NAME = "Palmtell";
export const APP_DESCRIPTION =
  "AI-powered palm reading — discover your personality, life path, and career insights from your palm.";
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

export const DISCLAIMER =
  "Palmtell readings are generated by AI for entertainment purposes only. Not medical, psychological, financial, or legal advice.";

export const PLANS = {
  basic: {
    name: "Basic",
    price: 0.99,
    features: [
      "Palm analysis: Personality, Life Path, Career",
      "1 reading per month",
      "Basic palm insights"
    ]
  },
  pro: {
    name: "Pro",
    price: 4.99,
    annualPrice: 48.00,
    features: [
      "Everything in Basic",
      "Relationships & Health sections",
      "Lucky Numbers",
      "Daily horoscope",
      "5 readings per month"
    ]
  },
  ultimate: {
    name: "Ultimate", 
    price: 8.99,
    annualPrice: 86.00,
    features: [
      "Everything in Pro",
      "Monthly horoscope forecast",
      "PDF export of readings",
      "Unlimited readings per month"
    ]
  }
} as const;

export const ZODIAC_SIGNS = [
  "aries",
  "taurus",
  "gemini",
  "cancer",
  "leo",
  "virgo",
  "libra",
  "scorpio",
  "sagittarius",
  "capricorn",
  "aquarius",
  "pisces",
] as const;

export type ZodiacSign = (typeof ZODIAC_SIGNS)[number];
